---
kind: Service
apiVersion: v1
metadata:
  name: hello-node
spec:
  type: NodePort
  selector:
    app: hello-node
  ports:
  - name: nodejs
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30002
